/* Creamos algunos usuarios con sus roles */
INSERT INTO `users` (username, password, enabled) VALUES ('andres','$2a$10$O9wxmH/AeyZZzIS09Wp8YOEMvFnbRVJ8B4dmAMVSGloR62lj.yqXG',1);
INSERT INTO `users` (username, password, enabled) VALUES ('admin','$2a$10$DOMDxjYyfZ/e7RcBfUpzqeaCs8pLgcizuiQWXPkU35nOhZlFcE9MS',1);
INSERT INTO `users` (username, password, enabled) VALUES ('jaime','$2a$10$O9wxmH/AeyZZzIS09Wp8YOEMvFnbRVJ8B4dmAMVSGloR62lj.yqXG',1);
INSERT INTO `users` (username, password, enabled) VALUES ('triston','$2a$10$DOMDxjYyfZ/e7RcBfUpzqeaCs8pLgcizuiQWXPkU35nOhZlFcE9MS',1);

INSERT INTO `authorities` (user_id, authority) VALUES (1,'ROLE_USER');
INSERT INTO `authorities` (user_id, authority) VALUES (3,'ROLE_USER');
INSERT INTO `authorities` (user_id, authority) VALUES (4,'ROLE_USER');
INSERT INTO `authorities` (user_id, authority) VALUES (2,'ROLE_ADMIN');
INSERT INTO `authorities` (user_id, authority) VALUES (2,'ROLE_USER');

INSERT INTO type_blog (name) VALUES ('Blog personal');
INSERT INTO type_blog (name) VALUES ('Blog profesional');
INSERT INTO type_blog (name) VALUES ('Blog corporativo');
INSERT INTO type_blog (name) VALUES ('Blog comercial');
INSERT INTO type_blog (name) VALUES ('Blog de nicho');

insert into blogs (name, description, url, type_blog_id ) values ('Real Estate Investment Trusts', 'Mech compl of unspecified cardiac device, initial encounter', 'http://dummyimage.com/195x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Apparel', 'Unspecified injury of left carotid artery, sequela', 'http://dummyimage.com/115x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Business Services', 'Path fracture in neoplastic disease, unsp ulna and radius', 'http://dummyimage.com/186x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Business Services', 'Other benign neoplasm of skin of unspecified part of face', 'http://dummyimage.com/189x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Real Estate Investment Trusts', 'Poisoning by other opioids, assault, sequela', 'http://dummyimage.com/246x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Marine Transportation', 'Other chondrocalcinosis, unspecified wrist', 'http://dummyimage.com/114x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Toxic effect of organophos and carbamate insect, asslt, sqla', 'http://dummyimage.com/201x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Clothing/Shoe/Accessory Stores', 'Superficial foreign body, left hip, initial encounter', 'http://dummyimage.com/163x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Commercial Banks', 'Nondisp fx of distal pole of navicular bone of r wrist, init', 'http://dummyimage.com/147x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Oth fracture of unsp lum vertebra, subs for fx w routn heal', 'http://dummyimage.com/214x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Oil/Gas Transmission', 'Part traum amp at lev betw elbow and wrist, right arm, init', 'http://dummyimage.com/115x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Consumer Electronics/Video Chains', 'Activity, piano playing', 'http://dummyimage.com/177x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Electronic Components', 'Personal history of neglect in childhood', 'http://dummyimage.com/224x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Clothing/Shoe/Accessory Stores', 'Disp fx of olecran pro w intartic extn unsp ulna, 7thP', 'http://dummyimage.com/233x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Oil & Gas Production', 'Social phobia, unspecified', 'http://dummyimage.com/211x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Investment Managers', 'Injury of cutan sensory nerve at forarm lv, unsp arm, init', 'http://dummyimage.com/155x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Steel/Iron Ore', 'Primary blast injury of fallopian tube, unsp, init encntr', 'http://dummyimage.com/199x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Asphyxiation due to plastic bag, intentional self-harm, init', 'http://dummyimage.com/179x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Real Estate Investment Trusts', 'External constriction of unsp front wall of thorax, init', 'http://dummyimage.com/111x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Inj oth musc/tend post grp at low leg level, right leg, sqla', 'http://dummyimage.com/151x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Textiles', 'Asphyx due to being trapped in bed linens, assault, sequela', 'http://dummyimage.com/186x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Apparel', 'Endodontic underfill', 'http://dummyimage.com/184x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Person outside pk-up/van inj in clsn w hv veh nontraf, subs', 'http://dummyimage.com/131x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Displaced oth extrartic fracture of unsp calcaneus, init', 'http://dummyimage.com/213x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Electric Utilities: Central', 'Disp fx of lateral end of unsp clavicle, init for clos fx', 'http://dummyimage.com/228x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Property-Casualty Insurers', 'Conjunctivochalasis, unspecified eye', 'http://dummyimage.com/233x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Drown due to fall/jump fr burning canoe or kayak, subs', 'http://dummyimage.com/234x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Ordnance And Accessories', 'Corrosion of unspecified degree of right foot', 'http://dummyimage.com/157x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Savings Institutions', 'Senile ectropion of left eye, unspecified eyelid', 'http://dummyimage.com/191x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Department/Specialty Retail Stores', 'Abrasion of abdomen, low back, pelvis and external genitals', 'http://dummyimage.com/118x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Auto Manufacturing', 'Other cervical disc disorders, mid-cervical region', 'http://dummyimage.com/250x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Pneumonia, unspecified organism', 'http://dummyimage.com/126x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Maternal care for oth rhesus isoimmun, first tri, fetus 5', 'http://dummyimage.com/159x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Hypothermia, initial encounter', 'http://dummyimage.com/128x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Partial traumatic amputation of scrotum and testis, subs', 'http://dummyimage.com/184x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Unsp comp following infusion and therapeutic injection', 'http://dummyimage.com/130x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Investment Bankers/Brokers/Service', 'Toxic effect of contact with other venomous animals, assault', 'http://dummyimage.com/248x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Banks', 'Central cord syndrome at C5, sequela', 'http://dummyimage.com/188x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Investment Bankers/Brokers/Service', 'Nondisp fx of base of nk of unsp femr, 7thG', 'http://dummyimage.com/220x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Business Services', 'Fracture of unspecified phalanx of left thumb, sequela', 'http://dummyimage.com/146x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Business Services', 'Juvenile arthritis, unspecified, unspecified wrist', 'http://dummyimage.com/138x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Other specified acquired deformities of unspecified limb', 'http://dummyimage.com/192x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Nondisp transverse fx shaft of unsp rad, 7thH', 'http://dummyimage.com/223x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Acute angle-closure glaucoma, bilateral', 'http://dummyimage.com/212x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Contact with scissors', 'http://dummyimage.com/203x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Business Services', 'Secondary malignant neoplasm of left ovary', 'http://dummyimage.com/149x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Inj oth blood vessels at hip and thigh level, unsp leg, init', 'http://dummyimage.com/172x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Contusion of adrenal gland, initial encounter', 'http://dummyimage.com/224x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Unspecified fracture of pubis', 'http://dummyimage.com/148x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Oth fx shaft of right tibia, subs for clos fx w malunion', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Precious Metals', 'Hemiplga following cerebral infrc affecting left nondom side', 'http://dummyimage.com/144x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Aerospace', 'Other fracture of right great toe, sequela', 'http://dummyimage.com/200x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Unsp inj flxr musc/fasc/tend l lit fngr at forarm lv, subs', 'http://dummyimage.com/202x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Other Consumer Services', 'Fracture of base of skull, unspecified side', 'http://dummyimage.com/123x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Hotels/Resorts', 'Inhalant abuse with intoxication delirium', 'http://dummyimage.com/241x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Real Estate', 'Oth osteopor w crnt path fx, l hand, subs for fx w nonunion', 'http://dummyimage.com/119x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Electric Utilities: Central', 'Fall from cliff, sequela', 'http://dummyimage.com/204x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Real Estate Investment Trusts', 'Abscess of tendon sheath', 'http://dummyimage.com/135x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Medical Specialities', 'Injury of digital nerve of unspecified finger, init encntr', 'http://dummyimage.com/146x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Unspecified subluxation of left ring finger, subs encntr', 'http://dummyimage.com/159x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Savings Institutions', 'Open bite of right thumb with damage to nail', 'http://dummyimage.com/127x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Investment Bankers/Brokers/Service', 'Fracture of ramus of mandible, unspecified side, 7thD', 'http://dummyimage.com/125x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'War op w dest arcrft due to clsn w oth aircraft, milt, subs', 'http://dummyimage.com/139x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Industrial Machinery/Components', 'Fracture of condylar process of right mandible, 7thB', 'http://dummyimage.com/247x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Banks', 'Unsp superficial injuries of r frnt wl of thorax, init', 'http://dummyimage.com/217x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Toxic effect of carb monx from incmpl combst dmst fuel, acc', 'http://dummyimage.com/128x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Other fall on same level', 'http://dummyimage.com/191x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Banks', 'Contusion of thoracic trachea, initial encounter', 'http://dummyimage.com/187x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Displaced avulsion fracture of right ilium', 'http://dummyimage.com/182x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Military/Government/Technical', 'Strain flexor musc/fasc/tend at forarm lv, right arm, sqla', 'http://dummyimage.com/123x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Investment Managers', 'Penetrating wound of orbit w or w/o fb, left eye, subs', 'http://dummyimage.com/238x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Specialty Chemicals', 'Illness, unspecified', 'http://dummyimage.com/111x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Medical/Dental Instruments', 'Herpesviral infection of penis', 'http://dummyimage.com/121x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Semiconductors', 'Eosinophilic colitis', 'http://dummyimage.com/186x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Natural Gas Distribution', 'Burn of third degree of upper back, sequela', 'http://dummyimage.com/126x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Banks', 'Sltr-haris Type II physl fx lower end of unsp tibia, sequela', 'http://dummyimage.com/211x100.png/dddddd/000000',2);
insert into blogs (name, description, url, type_blog_id ) values ('Medical/Dental Instruments', 'Disp fx of med epicondyl of unsp humer, 7thD', 'http://dummyimage.com/195x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Retinal artery branch occlusion', 'http://dummyimage.com/189x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Displ spiral fx shaft of ulna, r arm, 7thQ', 'http://dummyimage.com/106x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Oil & Gas Production', 'Meningococcal infection, unspecified', 'http://dummyimage.com/108x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Neonatal jaundice due to excessive hemolysis, unspecified', 'http://dummyimage.com/241x100.png/dddddd/000000',2);
insert into blogs (name, description, url, type_blog_id ) values ('Computer Software: Programming, Data Processing', 'Displ transverse fx shaft of r rad, 7thF', 'http://dummyimage.com/155x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Consumer Specialties', 'Other specified erythematous conditions', 'http://dummyimage.com/107x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('EDP Services', 'Displ transverse fx shaft of r femr, 7thJ', 'http://dummyimage.com/247x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Professional Services', 'Bipolar disorder', 'http://dummyimage.com/128x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Biotechnology: Electromedical & Electrotherapeutic Apparatus', 'Path fx in neopltc dis, r ankle, subs for fx w delay heal', 'http://dummyimage.com/176x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('Computer Software: Prepackaged Software', 'Strain of musc/tend peroneal grp at low leg level, left leg', 'http://dummyimage.com/103x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Displacement of implnt elec nstim of prph nrv lead, sequela', 'http://dummyimage.com/167x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Oil Refining/Marketing', 'Abrasion of right wrist', 'http://dummyimage.com/184x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Burn of first degree of unsp thumb (nail), subs encntr', 'http://dummyimage.com/120x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Major Pharmaceuticals', 'Toxic effect of unsp alcohol, intentional self-harm, sequela', 'http://dummyimage.com/250x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Biotechnology: Biological Products (No Diagnostic Substances)', 'Displacement of implanted urinary sphincter, subs', 'http://dummyimage.com/221x100.png/5fa2dd/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Unsp car occ injured in clsn w ped/anml in traf, sequela', 'http://dummyimage.com/240x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Engineering & Construction', 'Malignant neoplasm of branchial cleft', 'http://dummyimage.com/245x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Nondisp midcervical fx r femr, 7thR', 'http://dummyimage.com/143x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Other Pharmaceuticals', 'Disp fx of lateral condyle of l femr, 7thD', 'http://dummyimage.com/108x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Dislocation of MCP joint of right index finger, init', 'http://dummyimage.com/110x100.png/ff4444/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Computer Software: Programming, Data Processing', 'Schizoaffective disorders', 'http://dummyimage.com/208x100.png/dddddd/000000',1);
insert into blogs (name, description, url, type_blog_id ) values ('n/a', 'Cystocele, unspecified', 'http://dummyimage.com/115x100.png/cc0000/ffffff',1);
insert into blogs (name, description, url, type_blog_id ) values ('Newspapers/Magazines', 'Maternal care for oth fetal problems, unsp tri, fetus 2', 'http://dummyimage.com/110x100.png/ff4444/ffffff',1);

INSERT INTO usuario_blog (blogs, users) VALUES (1,2);
INSERT INTO usuario_blog (blogs, users) VALUES (2,2);
